# Generated by Django 5.2.6 on 2025-09-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='requiere_guia',
            field=models.BooleanField(default=False),
        ),
    ]
