# Generated by Django 5.2.6 on 2026-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sector_requiere_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='es_administradora_general',
            field=models.BooleanField(default=False),
        ),
    ]
