# Generated by Django 5.2.6 on 2025-10-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_sector_requiere_guia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instalacion__isnull', False), ('role', 'guardia')), models.Q(('role', 'guardia'), _negated=True), _connector='OR'), name='guardia_requires_instalacion'),
        ),
    ]
