# Generated by Django 5.2.6 on 2025-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_guardia_requires_instalacion'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_sector_requiere_guia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='guardia_requires_instalacion',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instalacion__isnull', False), ('role', 'guardia')), models.Q(('role', 'guardia'), _negated=True), ('is_superuser', True), _connector='OR'), name='guardia_requires_instalacion'),
        ),
    ]
