# Generated by Django 5.2.6 on 2026-03-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_guardia_requires_instalacion_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_empresa_es_administradora_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.sector'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guardia', 'Guardia'), ('admin', 'Administrador'), ('superadmin', 'SuperAdministrador'), ('cliente_sector', 'Cliente Sector')], default='guardia', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'cliente_sector'), ('sector__isnull', False)), models.Q(('role', 'cliente_sector'), _negated=True), ('is_superuser', True), _connector='OR'), name='cliente_sector_requires_sector'),
        ),
    ]
