# Generated by Django 5.2.6 on 2025-09-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProhibicionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('dni_extranjero', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('es_extranjero', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('empresa', models.CharField(blank=True, max_length=120, null=True)),
                ('patente', models.CharField(blank=True, max_length=12, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('residente', 'Residente'), ('prohibido', 'Prohibido')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida')], max_length=10)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='core.empresa')),
            ],
        ),
    ]
