# Generated by Django 5.2.6 on 2025-09-29 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_ctrl', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceso',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='core.instalacion'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='core.sector'),
        ),
        migrations.AddField(
            model_name='prohibicionacceso',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibiciones', to='core.instalacion'),
        ),
        migrations.AddField(
            model_name='prohibicionacceso',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prohibiciones', to='access_ctrl.visita'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='access_ctrl.visita'),
        ),
        migrations.AddIndex(
            model_name='prohibicionacceso',
            index=models.Index(fields=['instalacion', 'fecha_inicio'], name='access_ctrl_instala_1650d0_idx'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['instalacion', 'fecha_hora'], name='access_ctrl_instala_5ac327_idx'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['empresa', 'fecha_hora'], name='access_ctrl_empresa_fa5932_idx'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['tipo', 'fecha_hora'], name='access_ctrl_tipo_de8f7d_idx'),
        ),
    ]
