# Generated by Django 5.2.6 on 2025-10-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_ctrl', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='foto_url',
            field=models.JSONField(blank=True, default=list, help_text='Permite guardar una o más URLs de fotos (compatible con SQLite y PostgreSQL)', null=True),
        ),
    ]
