# Generated by Django 5.2.6 on 2026-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_ctrl', '0003_alter_acceso_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
