# Generated by Django 5.2.6 on 2026-03-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_ctrl', '0004_visita_comentario'),
        ('core', '0003_empresa_es_administradora_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='core.instalacion'),
        ),
        migrations.AddField(
            model_name='visita',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='core.sector'),
        ),
    ]
